homeでのuploadと同時にstatenoaudiosに追加して描画するようにした
ykpythemind/auf pull request #37
Opened 2017-07-24 13:38 UTC by kei-tamiya

#28

2017-07-24 13:43 UTC, kei-tamiya commented
見てたやつ
https://github.com/vuejs/Discussion/issues/292

2017-07-25 02:58 UTC, ykpythemind requested changes
さらっと見た

2017-07-25 02:58 UTC, ykpythemind commented on app/javascript/packs/components/Uploadform.vue
> +    name: 'Uploadform',
完全な勘ですがローワーキャメルケースのほうがいいんでは？

2017-07-25 02:58 UTC, ykpythemind commented on app/javascript/packs/components/Uploadform.vue
> +      this.$data.audio.description = this.defaultDescription
行末に;

2017-07-25 02:58 UTC, ykpythemind commented on app/javascript/packs/components/Uploadform.vue
> +    name: 'Uploadform',
UploadFormとUploadformなど混在しててぼく命名規則よくわからん

2017-07-25 02:58 UTC, ykpythemind commented on app/javascript/packs/components/Uploadform.vue
> +        const q = JSON.parse(JSON.stringify(audio));
もっと$dataの持ち方とかがシンプルだと行けるとかないですか？ 自分のこと棚に上げまくってるので全然いいとおもいます
さらっと見ただけなのでやはりvuexワカンネ！

2017-07-25 06:17 UTC, kei-tamiya commented on app/javascript/packs/components/Uploadform.vue
> +    name: 'Uploadform',
UploadFormって書いてたつもりでした

[これvuexリポジトリのexample](https://github.com/vuejs/vuex/blob/dev/examples/todomvc/components/Todo.vue)

がアッパーキャメルだったから真似しておりました

2017-07-25 06:18 UTC, kei-tamiya commented on app/javascript/packs/components/Uploadform.vue
> +        const q = JSON.parse(JSON.stringify(audio));
なんか前みたいにこのUploadForm.vue内で$.ajax使ってた時は普通に行けたのに切り出したらうまくオブジェクト渡せなかった。。もうちょっと試すわ　ここ絶対うまくできる気がする

2017-07-25 06:18 UTC, kei-tamiya commented on app/javascript/packs/components/Uploadform.vue
> +      this.$data.audio.description = this.defaultDescription
あざす

2017-07-25 06:26 UTC, kei-tamiya commented on app/javascript/packs/components/Uploadform.vue
> +    name: 'Uploadform',
メソッド系はローワーキャメルケース、
vueコンポーネントファイル自体とかそのnameプロパティとかはアッパーキャメルケースなイメージで使ってた

2017-07-25 07:42 UTC, kei-tamiya commented
@ykpythemind 修正しました。暇な時軽く見てくださいな
オブジェクトで渡して`JSON.parse()`無くしました、
ついでfetchしてた部分も同様に引数をオブジェクトにしてコード整えましたー。

`$.ajax`のfail時とかのメッセージは別Issueでやります

2017-07-25 08:35 UTC, ykpythemind commented on app/javascript/packs/components/AudioComponent.vue
> +        h6.float-right {{ audio.created_at | moment }}
`{{ audio.created_at | moment }}` フィルタきもちいいっすね・・・

2017-07-25 08:37 UTC, ykpythemind approved these changes

2017-07-25 08:38 UTC, merged